name: Digger Destroy
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Digger project to perform destroy on'
        required: true
jobs:
  destroy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: lumeweb/akash-action@v0.1.3
        with:
          mnemonic: ${{ secrets.AKASH_WALLET_SEED }}
          cert-content: ${{ secrets.AKASH_CERT_CONTENT }}
          cert-id: ${{ secrets.AKASH_CERT_ID }}
      - name: Process Akash Providers
        id: providers
        run: >
          PROVIDERS=$(yq eval '.providers[].address' config/akash-providers.yaml | jq
          -R -s -c 'split("\n")[:-1]')

          echo "PROVIDER_LIST=${PROVIDERS}" >> $GITHUB_ENV
      - name: digger destroy
        uses: LumeWeb/digger-action@v0.1.3
        with:
          mode: manual
          command: "digger destroy"
          project: "${{ inputs.project }}"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          digger-version: v0.6.62
          secrets-context: ${{ toJson(secrets) }}
          variables-context: ${{ toJson(vars) }}
          aws-endpoint-url: ${{ secrets.AWS_ENDPOINT_URL }}
          aws-bucket: ${{ secrets.AWS_BUCKET }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_REGION: us-east-1